### PR TITLE
Standalone forward decls

### PR DESCRIPTION
**Pull request by eddyz87**
Just running CI again, hoping 10001 != expected 10000 would go away :)

### CODE REVIEW

**Comment by chantra** [comment]
@eddyz87 I started introducing runners that have kvm enabled. The pro is that it runs faster, but unfortunately, it seems that there is a different behaviour when the VM runs under KVM or full qemu emulation.

You should rebase on top of https://github.com/kernel-patches/vmtest/commit/36c28cf80345d0ccc41e61b7603a806cccbe371a 

It also includes a DENYLIST for aarch64, which should be coming soonish.

**Comment by eddyz87** [comment]
@chantra , noted, thanks for the info!

**Comment by danielocfb** [comment]
This pull request seems to have been superseded by https://github.com/kernel-patches/bpf/pull/3964, so I am closing it. Normally I wouldn't care much, but trying to better understand some duplicate pull request creation we have seen. Feel free to reopen if you still need it.

**Comment by eddyz87** [comment]
> This pull request seems to have been superseded by #3964, so I am closing it. Normally I wouldn't care much, but trying to better understand some duplicate pull request creation we have seen. Feel free to reopen if you still need it.

Ok, sorry for spam in merge requests, I've seen that these are closed by an automata after some period of time so did not pay much attention. By the way, I have not noticed any erroneous creation of duplicates, at least for my MRs.

**Comment by danielocfb** [comment]
> > This pull request seems to have been superseded by #3964, so I am closing it. Normally I wouldn't care much, but trying to better understand some duplicate pull request creation we have seen. Feel free to reopen if you still need it.
> 
> Ok, sorry for spam in merge requests, I've seen that these are closed by an automata after some period of time so did not pay much attention.

Not a problem at all. We want the CI to be used and that is kind of the intended workflow. I was just cleaning up. We will hopefully do that automatically soon, but it hasn't been implemented. So in a sense...leaving these open provides more incentive for us to fix this shortcoming ;-)

> By the way, I have not noticed any erroneous creation of duplicates, at least for my MRs.

Thanks for the feedback. It seems to have been a one-off thing caused by the change in base line branch against which pull requests are created.

**Pull request closed without merging**
