### PR TITLE
Standalone forward decls

### PR DESCRIPTION
**Pull request by eddyz87**
CI...

### CODE REVIEW

**Comment by danielocfb** [comment]
Hi @eddyz87! I see you created a pull request directly against the `bpf-next_base` branch. I am happy to see it being used, as the creation of which is a recent addition and has not yet been publicized. I am curious if you can share any feedback: did this simplify your workflow (I see you are a more or less regular CI user)? I am working on documenting good practices for running the CI before patch submission and getting that in the upstream BPF documentation. I'd be happy to incorporate your feedback if you have any.

**Comment by eddyz87** [comment]
Hi @danielocfb,

> I see you created a pull request directly against the bpf-next_base branch. I am happy to see it being used, as the creation of which is a recent addition and has not yet been publicized.

I've got a tip from Mykola Lysenko that such feature is in progress and I've noticed in the pull requests log that requests for bpf-next_base execute CI automatically, so I decided to make use of it. Sorry if this interfered with some of your work, I can stop and wait until you make this official.

> I am curious if you can share any feedback: did this simplify your workflow (I see you are a more or less regular CI user)? I am working on documenting good practices for running the CI before patch submission and getting that in the upstream BPF documentation. I'd be happy to incorporate your feedback if you have any.

It is great! It is much more convenient then before. Thank you for implementing it :)
TBH, I have nothing to complain about, it just works.

The only quirk is that I have to cherry-pick two commits from Andrii to make test_progs compile: [1](https://github.com/kernel-patches/bpf/pull/3964/commits/02f6543d6622164f443d55c0fb1c54a33961d745), [2](https://github.com/kernel-patches/bpf/pull/3964/commits/caedf7eee3b1fa96393b5e6244c0326fb75be0f1), but as far as I understand this has nothing to do with CI but is a problem with current state of bpf-next and would be resolved eventually.

**Comment by danielocfb** [comment]
> > I see you created a pull request directly against the bpf-next_base branch. I am happy to see it being used, as the creation of which is a recent addition and has not yet been publicized.
> 
> I've got a tip from Mykola Lysenko that such feature is in progress and I've noticed in the pull requests log that requests for bpf-next_base execute CI automatically, so I decided to make use of it. Sorry if this interfered with some of your work, I can stop and wait until you make this official.
> 
> > I am curious if you can share any feedback: did this simplify your workflow (I see you are a more or less regular CI user)? I am working on documenting good practices for running the CI before patch submission and getting that in the upstream BPF documentation. I'd be happy to incorporate your feedback if you have any.
> 
> It is great! It is much more convenient then before. Thank you for implementing it :) TBH, I have nothing to complain about, it just works.

Awesome! Great to hear. Feel free to continue; no interference.

> The only quirk is that I have to cherry-pick two commits from Andrii to make test_progs compile: [1](https://github.com/kernel-patches/bpf/pull/3964/commits/02f6543d6622164f443d55c0fb1c54a33961d745), [2](https://github.com/kernel-patches/bpf/pull/3964/commits/caedf7eee3b1fa96393b5e6244c0326fb75be0f1), but as far as I understand this has nothing to do with CI but is a problem with current state of bpf-next and would be resolved eventually.

Ah, interesting. That should have been a temporary measure to mitigate a defect in the upstream branch. By now these patches are in the CI repository (https://github.com/kernel-patches/vmtest/pull/159), so this should no longer be necessary (but also shouldn't hurt).

**Comment by eddyz87** [comment]
> Ah, interesting. That should have been a temporary measure to mitigate a defect in the upstream branch. By now these patches are in the CI repository (https://github.com/kernel-patches/vmtest/pull/159), so this should no longer be necessary (but also shouldn't hurt).

Noted, thank you!
I'll try the next run w/o these patches.

**Comment by eddyz87** [comment]
Hi @danielocfb ,

Just a heads up, there is an issue with LLVM build right now that manifest itself on several pipelines: [1](https://github.com/kernel-patches/bpf/actions/runs/3424973431/jobs/5705282111), [2](https://github.com/kernel-patches/bpf/actions/runs/3423703581/jobs/5702603659), [3](https://github.com/kernel-patches/bpf/actions/runs/3425123520/jobs/5705585259).

I found an email thread with a fix for it: [here](https://lore.kernel.org/lkml/20221109000306.1407357-1-nathan@kernel.org/T/#u). Looks like it is a regression introduced yesterday in the kernel mainline. [Here](https://github.com/kernel-patches/bpf/actions/runs/3427670245/jobs/5710961893) is a successful build with this fix. My guess is that mainline will accept either this fix or something similar soon, but I wanted to share the knowledge as I already spent some time investigating.

**Pull request closed without merging**
